piro20_Ajax_Pirostagram/apps/posts/urls.py
from django.urls import path,include
from .views import *

app_name='posts'

urlpatterns = [
    path('', main, name="main"),
    path('create/', create, name="create"),
    path('write_comment/', write_comment, name="comment"),
    path('change_like/', change_like, name="like"),
    path('delete_comment/', delete_comment, name="delete_comment"),
]

piro20_Ajax_Pirostagram/apps/users/urls.py
from django.urls import path,include
from .views import *

app_name='users'

urlpatterns = [
    path('', main, name="main"),
    path('signup/', signup, name="signup"),
    path('login/', login, name="login"),
    path("logout/", logout, name="logout"),
]

piro20_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("apps.posts.urls")),
    path('users/',include("apps.users.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piro20_Ajax_Pirostagram/apps/posts/models.py
from django.db import models
from apps.users.models import User

class Post(models.Model):
    image=models.ImageField('이미지', blank=True, upload_to='posts/%Y%m%d')
    content=models.TextField('내용',max_length=100)
    created_date=models.DateTimeField("작성일", auto_created=True, auto_now_add=True)
    updated_date=models.DateTimeField("수정일", auto_created=True, auto_now=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='작성유저')
    likes = models.IntegerField(default=0)
    like_users = models.ManyToManyField(User, related_name='like_articles')

class Comment(models.Model):
    comment_user=models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="댓글 작성 유저")
    content=models.CharField(max_length=50, null=False)
    post=models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="게시글")
    

# Create your models here.

piro20_Ajax_Pirostagram/apps/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image=models.ImageField('이미지', blank=True, upload_to='users/%Y%m%d')
    name = models.CharField(max_length=10, null=False)


    def __str__(self):
        return self.name

piro20_Ajax_Pirostagram/apps/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta():
        model=Post
        fields=['image','content',]
        

piro20_Ajax_Pirostagram/apps/users/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm

class SignupForm(UserCreationForm):
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'image', 'name',]

piro20_Ajax_Pirostagram/apps/posts/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import PostForm
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

# Create your views here.
def main(request):
    posts=Post.objects.all()
    return render(request, "posts/main.html", {'posts':posts})

def create(request):
    if request.method=="POST":
        form=PostForm(request.POST, request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.user=request.user
            post.save()
        return redirect('posts:main')
    
    form=PostForm()
    return render(request, "posts/create.html", {'form':form})
    


@login_required
@csrf_exempt
def write_comment(request):
    if request.method=="POST":
        req=json.loads(request.body)
        post_id=req['id']
        comment=req['comment']
        user=request.user
        post=Post.objects.get(id=post_id)
        
        new_comment=Comment.objects.create(content=comment, comment_user=user, post=post )
        user.comment=new_comment
        post.comment=new_comment
        post.save()
        user.save()
        print(user.comment)
        return JsonResponse({'id':post_id, 'text':comment, 'comment_id':new_comment.id})
    

@login_required
@csrf_exempt
def change_like(request):
    if request.method=="POST":
        req=json.loads(request.body)
        post_id=req['id']
        updown=req['num']
        
        user=request.user
        post=Post.objects.get(id=post_id)
        
        if updown==1:
            post.like_users.add(request.user)
            post.likes+=1
        else:
            post.likes-=1
            post.like_users.remove(request.user)
        post.save()
        return JsonResponse({'id':post_id, 'num':post.likes})
    
@login_required
@csrf_exempt
def delete_comment(request):
    if request.method=="POST":
        req=json.loads(request.body)
        post_id=req['pid']
        comment_id=req['cid']
        comment=Comment.objects.get(id=comment_id)
        comment.delete()
        return JsonResponse({'id':post_id})

piro20_Ajax_Pirostagram/apps/users/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth

# Create your views here.
def main(request):
    return redirect('posts:main')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('users:main')
        else:
            ctx={
                'form':form,
            }
            return render(request, 'users/signup.html',context=ctx) # 이부분 수정
    else:
        form = SignupForm()
        context={
            'form': form,
        }
        return render(request, template_name='users/signup.html', context=context)
    
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('users:main')
        else:
            context = {
                'form': form,
            }
            return render(request, template_name='users/login.html', context=context)
    else:
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, template_name='users/login.html', context=context)
    
    
def logout(request):
    auth.logout(request)
    return redirect('posts:main')

piro20_Ajax_Pirostagram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="{%static 'css/nomalize.css'%}">  
  <link rel="stylesheet" href="{%static 'css/style.css'%}">  
  {%block head%}


  {% endblock %}    
</head>
<body>
  <main>
    <header>
      <a href="" id='logo1' ></a>
      {% if user.is_authenticated %}
        <a href="/create" id='logo2' style='text-decoration: none;' ></a>
        <a href="/users/logout" id='logo3' style='text-decoration: none;'></a>
      {% else %}
        <a href="/users/signup" id='logo4' style='text-decoration: none;' > 계정 등록</a>
        <a href="/users/login" id='logo5' style='text-decoration: none;'> 로그인 </a>
      {% endif %}
      <p> 현재 로그인 <br/> <strong>{{user.name}}</strong> </p>
      {% if user.image %}
        <img src="{{user.image.url}}" />
      {% else %}
        <img src="/media/no_image.png"/>
      {% endif %}
    </header>
    <div class="body">
      <div class="story">
        <div class="story__container">
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum1/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum2/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum3/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum4/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum5/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum6/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum7/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum8/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum9/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
            <div class="story__content">
                <div class="story__img"><img src="https://picsum.photos/seed/picsum10/200/300" alt=""></div>
                <div class="story__title">여행</div>
            </div>
        </div>
      </div>
    {%block content%}
      
    
    {%endblock%}
    </div>
  </main>
  <footer>
  </footer>
  
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  <script defer src="{%static '/js/script.js'%}"></script> 
  <script src="https://kit.fontawesome.com/26acdb4290.js" crossorigin="anonymous"></script> 
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </body>    
</html>

piro20_Ajax_Pirostagram/templates/posts/create.html
{% extends 'base.html' %}
{%block head%}
  <title>post_create</title>
{% endblock %}

{%block content%}
<div class="content-wrapper">
  <div class="wrapper-header">
    <h2>Post Register</h2>
  </div>
  <form
    action="{% url 'posts:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </nctype=>
</div>
{%endblock%}

piro20_Ajax_Pirostagram/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{%block head%}
  <title>PiroStagram</title>
{% endblock %}

{%block content%}
  <div class="content-wrapper">
    <!-- 글 목록 -->
    {% for post in posts %}
        <div id="posting" class="post-{{post.id}}">
            <div id="post_header">
                {% if post.user.image %} 
                    <img src="{{post.user.image.url}}" style="width:25px; height:25px;">
                {% else %}
                    <img src="/media/no_image.png" style="width:25px; height:25px;">
                {% endif %}
                <p><strong>{{post.user}} </strong></p>
            </div>
            <div class="post_content">
                {% if post.image %}
                    <img src="{{post.image.url}}" >
                {% else %}
                    <img src="/media/no_image.png">
                {% endif %}
                <div class="like">
                    {% if user in post.like_users.all %}
                        <input type="checkbox" class="heart" id="myCheck-{{post.id}}" checked></input>
                    {% else %}
                        <input type="checkbox" class="heart" id="myCheck-{{post.id}}"></input>
                    {% endif %} 
                        
                    <label for="myCheck-{{post.id}}" onclick="change_like({{post.id}})"></label>
                    <p>좋아요:</p>
                    <p id="like-num-{{post.id}}">{{post.likes}}</p>
                    <p>개</p>
                </div>
                <p><strong>{{post.user}}  </strong>{{post.content}}</p>
            </div>
            
            <div id="post_comments" class="post-{{post.id}}-comment"> 
                {% for comment in post.comment_set.all %}
                    <div class="comment-container" id="comment-{{post.id}}-{{comment.id}}">
                        <p><strong>{{comment.comment_user.name}}</strong> {{comment.content}} </p>
                        {% if comment.comment_user == user %}
                            <button type="button" onclick="delete_comment({{post.id}},{{comment.id}})">삭제</button>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div class="comment-write">
                <p><strong>{{user.name}} </strong></p>
                <input type="text" name="comment" placeholder="댓글 작성..." class="comment-write-{{post.id}}"/>
                <button type="button" onclick="commentUp({{post.id}},'{{user.name}}')"><i class="fa-regular fa-paper-plane"></i></button>
            </div>
        </div>
    {% endfor %}
  </div>
{%endblock%}

piro20_Ajax_Pirostagram/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="content-wrapper">
    <form method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <button type="submit" value="SignUp">Login</button>
    </form>
</div>
{% endblock content %}

piro20_Ajax_Pirostagram/templates/users/signup.html
{% extends 'base.html' %}
{%block head%}
  <title>post_create</title>
{% endblock %}

{%block content%}
<div class="content-wrapper">
  <div class="wrapper-header">
    <h2>Post Register</h2>
    <p>아이디어 등록 페이지입니다. 당신의 첫 번째 아이디어를 잊지말고 기록하세요!</p>
  </div>
  <form
    action="{% url 'users:signup' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </nctype=>
</div>
{%endblock%}