SWIDEA_SITE/apps/devtools/urls.py
from django.urls import path,include
from .views import *

app_name='devtools'

urlpatterns = [
    path('', main, name="main"),
    path('create/', create, name="create"),
    path('detail/<int:pk>', detail, name="detail"),
    path('update/<int:pk>', update, name="update"),
    path('delete/<int:pk>', delete, name="delete"),
    
]

SWIDEA_SITE/apps/ideas/urls.py
from django.urls import path,include
from .views import *

app_name='ideas'

urlpatterns = [
    path('', main, name="main"),
    path('create/', create, name="create"),
    path('detail/<int:pk>', detail, name="detail"),
    path('update/<int:pk>', update, name="update"),
    path('delete/<int:pk>', delete, name="delete"),
    path('change_interest/', change_interest, name='change_interest'),
    path('change_heart/', change_heart, name='change_heart'),
]

SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.ideas.urls')),
    path('devtools/', include('apps.devtools.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/apps/devtools/models.py
from django.db import models

# Create your models here.
class Devtool(models.Model):
    name=models.CharField('이름',max_length=24)
    kind=models.CharField('종류',max_length=24)
    content=models.CharField('개발툴 설명',max_length=100)
    
    def __str__(self):
        return f'{self.name}'

SWIDEA_SITE/apps/ideas/models.py
from django.db import models
from apps.devtools.models import Devtool

# Create your models here.
class Idea(models.Model):
    title=models.CharField('아이디어명',max_length=24)
    image=models.ImageField('이미지', blank=True, upload_to='ideas/%Y%m%d')
    content=models.CharField('아이디어설명',max_length=100)
    interest=models.IntegerField('좋아요',default=0)
    devtool=models.ForeignKey(Devtool, on_delete=models.CASCADE, verbose_name='개발툴')
    created_date=models.DateTimeField("작성일", auto_created=True, auto_now_add=True)
    updated_date=models.DateTimeField("수정일", auto_created=True, auto_now=True)
    
class IdeaStar(models.Model):
    star=models.BooleanField(default=False)
    idea=models.OneToOneField(Idea, on_delete=models.CASCADE, related_name="ideastar")

SWIDEA_SITE/apps/devtools/forms.py
from django import forms
from .models import Devtool

class DevtoolForm(forms.ModelForm):
    class Meta():
        model=Devtool
        fields=('__all__')
        

SWIDEA_SITE/apps/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta():
        model=Idea
        fields=('__all__')
        

SWIDEA_SITE/apps/devtools/views.py
from django.shortcuts import render,redirect
from .models import Devtool
from .forms import DevtoolForm

# Create your views here.
def main(request):
    search_txt=request.GET.get('search_txt')
    devtools=Devtool.objects.all()
    if search_txt:
        devtools=devtools.filter(name__contains=search_txt)    
    return render(request, "devtools/devtool_list.html", {'devtools':devtools} )

def create(request):
    if request.method=="POST":
        form=DevtoolForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('devtools:main')
    
    form=DevtoolForm()
    ctx={'form':form}
    return render(request, "devtools/devtool_create.html", ctx)


def detail(request,pk):
    devtool=Devtool.objects.get(id=pk)
    related_ideas=devtool.idea_set.all()
    ctx={'devtool':devtool,
         'pk':pk,
         'related_ideas':related_ideas
         }
    return render(request, "devtools/devtool_detail.html",ctx)

def update(request, pk):
    devtool=Devtool.objects.get(id=pk)
    if request.method=="POST":
        form=DevtoolForm(request.POST, instance=devtool)
        if form.is_valid():
            form.save()
        return redirect("devtools:detail",pk)
    
    form=DevtoolForm(instance=devtool)
    ctx={'form':form,
         'pk':pk
         }    
    return render(request, 'devtools/devtool_update.html', ctx)

def delete(request,pk):
    if request.method=="POST":
        Devtool.objects.get(id=pk).delete()
    return redirect('devtools:main')
    
    

SWIDEA_SITE/apps/ideas/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .forms import IdeaForm
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
def main(request):
    sort = request.GET.get('sort','')
    if sort == 'title':
        ideas = Idea.objects.all().order_by('title')
    elif sort ==  'olddate':
        ideas = Idea.objects.all().order_by('created_date')
    elif sort == 'newdate':
        ideas = Idea.objects.all().order_by('-created_date')
    else:
        ideas = Idea.objects.all().order_by('-interest')
        
    page = request.GET.get('page')
    items_per_page = 4
    paginator = Paginator(ideas, items_per_page)
    try:
        # 현재 페이지에 해당하는 항목 가져오기
        items = paginator.page(page)
    except PageNotAnInteger:
        # 페이지 번호가 정수가 아닌 경우, 첫 번째 페이지로 설정
        items = paginator.page(1)
    except EmptyPage:
        # 페이지가 비어 있는 경우, 마지막 페이지로 설정
        items = paginator.page(paginator.num_pages)
    ctx={'ideas':items,
         'order_by_field': sort}
    return render(request, "ideas/idea_list.html", ctx)

def create(request):
    if request.method=="POST":
        form=IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            idea_now=form.save()
            ideastar=IdeaStar.objects.create(idea=idea_now)
        return redirect('ideas:main')
    
    form=IdeaForm()
    ctx={'form':form}
    return render(request, "ideas/idea_create.html", ctx)

def detail(request,pk):
    idea=Idea.objects.get(id=pk)
    ctx={'idea':idea,
         'pk':pk
         }
    return render(request, "ideas/idea_detail.html",ctx)

def update(request, pk):
    idea=Idea.objects.get(id=pk)
    if request.method=="POST":
        form=IdeaForm(request.POST, request.FILES, instance=idea)
        if form.is_valid():
            form.save()
        return redirect("ideas:detail",pk)
    
    form=IdeaForm(instance=idea)
    ctx={'form':form,
         'pk':pk
         }    
    return render(request, 'ideas/idea_update.html', ctx)

def delete(request,pk):
    if request.method=="POST":
        idea=Idea.objects.get(id=pk)
        idea.delete()
    return redirect('ideas:main')

def change_interest(request):
    dic=request.POST.dict()
    idea=Idea.objects.get(id=dic['field1'])
    idea.interest+=int(dic['field2'])
    idea.save()   
    return JsonResponse({'interest': idea.interest})

def change_heart(request):
    dic=request.POST.dict()
    idea=Idea.objects.get(id=dic['id'])
    ideastar=idea.ideastar
    if dic['heart']=="True":
        ideastar.star=True
    else:
        ideastar.star=False
    ideastar.save()
    return JsonResponse({'interest': idea.interest})
    
    

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="stylesheet" href="{%static 'ideas/css/style.css'%}">  
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script defer src="{%static 'ideas/js/script.js'%}"></script> 
  {%block head%}


  {% endblock %}    
</head>
<body>
  <main>
    <header>
      <a href="/" id='logo' style='text-decoration: none; color: red;'><h1>My SW Idea Manager</h1></a>
      <a href="/create" id='logo' style='text-decoration: none;' >아이디어 등록</a>
      <a href="/" id='logo' style='text-decoration: none;' >아이디어 관리</a>
      <a href="{% url "devtools:create" %}" id='logo' style='text-decoration: none;' >개발툴 등록</a>
      <a href="{% url "devtools:main" %}" id='logo' style='text-decoration: none;' >개발툴 관리</a>
    </header>
    {%block content%}
      
    
    {%endblock%}
  </main>
  <footer>
  </footer>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
</body>
</html>

SWIDEA_SITE/templates/devtools/devtool_create.html
{% extends 'base.html' %}
{%block head%}
  <title>devtool_create</title>
{% endblock %}

{%block content%}
  <div class="content-wrapper-2">
    <div class="wrapper-header">
      <h2>Devtool Register</h2>
      <p>개발툴 등록 페이지입니다. 자신이 다룰 수 있는 개발툴을 등록해보세요.</p>
    </div>
    <form
      action="{% url 'devtools:create' %}"
      method="post"
    >
      {%csrf_token%} {{form.as_p}}
      <button class="btn btn-success">등록하기</button>
  </div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="content-wrapper-2">
    <div class="wrapper-header">
      <h2>Devtool Detail</h2>
      <p>개발툴 세부내용 페이지입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을 확인해봐요.</p>
    </div>
    <div class="wrapper-middle-detail2">
      <h2>{{devtool.name}}</h2>
      <div id="details">
        <p>아이디어 관심도: {{devtool.kind}}</p>
        <p>예상 개발 툴: {{devtool.content}}</p>
      <p>만들 수 있는 SW 목록</p>
    
      {% for rel_idea in related_ideas %}
        <a href="{% url 'ideas:detail' rel_idea.pk %}" class="btn" style="background-color:white; color:black;">
          {{rel_idea.title}}
        </a>
      {% endfor %}
      </div>
    </div>
    <form action="{% url 'devtools:delete' devtool.pk %}" method="post">
      {%csrf_token%}
      <a href="{% url 'devtools:update' devtool.pk %}" class="btn btn-primary">수정</a>
      <a href="{% url 'devtools:main' %}" class="btn" style="background-color:white; color:black;">목록</a>
      <button type="submit" class="btn btn-danger">삭제</button>
    </form>
  </div>
{% endblock content %}

SWIDEA_SITE/templates/devtools/devtool_list.html
{% extends 'base.html' %}

{%block head%}
  <title>기술 리스트</title>
{% endblock %}

{%block content%}
  <div class="content-wrapper">
    <div class="wrapper-header">
      <h2>Devtool List</h2>
      <p>개발툴 목록 페이지입니다. 자신이 다룰 수 있는 개발툴에 대한 목록을 확인해보세요.</p>
    </div>
    <div class="search-box">    
      <form action="">      
        <input class = 'form-control mx-2' type="input" name="search_txt" placeholder="검색어를 입력하세요" />
        <input class = 'btn btn-outline-success mx-2' type="submit" value="검색" style="background-color:lightgray;"/>      
      </form>
    </div>
    <!-- 글 목록 -->
    {% for devtool in devtools %}
        <div class="info_devtool">
          <a href="{% url 'devtools:detail' devtool.pk %}" class="title">
            {{devtool.name}}
          </a>
          <p class="region"> {{devtool.kind}}</p>
          <p class="region"> {{devtool.content}}</p>
        </div>
    {% endfor %}

  </div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_update.html
{% extends 'base.html' %}
{%block head%}
  <title>devtool_create</title>
{% endblock %}

{%block content%}
  <div class="content-wrapper-2">
    <div class="wrapper-header">
      <h2>Devtool Detail Update</h2>
      <p>개발툴 세부내용 수정 페이지입니다. 개발 툴에 수정사항이 있다면 수정해보세요.</p>
    </div>
    <form
      action="{% url 'devtools:update' pk %}"
      method="post"
    >
      {%csrf_token%} {{form.as_p}}
      <button class="btn btn-success">수정하기</button>
  </div>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_create.html
{% extends 'base.html' %}
{%block head%}
  <title>idea_create</title>
{% endblock %}

{%block content%}
<div class="content-wrapper-2">
  <div class="wrapper-header">
    <h2>Idea Register</h2>
    <p>아이디어 등록 페이지입니다. 당신의 첫 번째 아이디어를 잊지말고 기록하세요!</p>
  </div>
  <form
    action="{% url 'ideas:create' %}"
    method="post"
    enctype="multipart/form-data"
  >
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </nctype=>
</div>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="content-wrapper-2">
    <div class="wrapper-header">
      <h2>Idea Detail</h2>
      <p>아이디어 세부내용 페이지입니다. 당신이 구현하려는 아이디어를 확인해보세요.</p>
    </div>
    <div class="wrapper-middle-detail">
      <div class="thumbnail" id="thumbnail" onmouseover="showStar({{idea.id}})" onmouseout="hideStar({{idea.id}})" onclick="toggleFavorite({{idea.id}})">
        {% if idea.image.url != null and idea.image.url != '' %}
          <img src="{{idea.image.url}}">
        {% else %}
          <img src="{% static "ideas/image/no_img.png" %}" alt="대체 텍스트">
        {% endif %}
        {% if idea.ideastar.star == True %}
          <div class="star" id="star-{{idea.id}}" style="display:block;">&#9734;</div>
        {% else %}
          <div class="star" id="star-{{idea.id}}" style="display:none;">&#9734;</div>
        {% endif %}
      </div>
      <div id="details">
        <h2 style="color:lightgreen"> {{idea.title}}</h2>
        <p>1) 아이디어 관심도: {{idea.interest}}</p>
        <p>2) 예상 개발 툴: <a href="{% url 'devtools:detail' idea.devtool.id %}">{{idea.devtool.name}}</a></p>
        <p class="my-3">3)아이디어 설명 : {{idea.content}}</p>
      </div>
    </div>
    <form action="{% url 'ideas:delete' idea.pk %}" method="post">
      {%csrf_token%}
      <a href="{% url 'ideas:update' idea.pk %}" class="btn btn-primary">수정</a>
      <a href="{% url 'ideas:main' %}" class="btn" style="background-color:white;">목록</a>
      <button type="submit" class="btn btn-danger">삭제</button>
    </form>
  </div>
{% endblock content %}

SWIDEA_SITE/templates/ideas/idea_list.html
{% extends 'base.html' %}
{% load static %}
{%block head%}
  <title>아이디어 리스트</title>
{% endblock %}

{%block content%}
  <div class="content-wrapper-2">
    <div class="wrapper-header">
      <h2>Idea List</h2>
      <p>나의 아이디어를 잊지 말고 기억해보세요</p>
      <select class="sort-select" onchange="location = this.value;">
        <option class="sort-interest" value="/">선호순</option>
        <option class="sort-title" value="?sort=title">이름순</option>
        <option class="sort-olddate" value="?sort=olddate">등록순</option>
        <option class="sort-newdate" value="?sort=newdate">최신순</option>
      </select>
    </div>
    <!-- 글 목록 -->
    <div class="wrapper-middle">
      {% for idea in ideas %}
        <div class="item">
          <div class="thumbnail" id="thumbnail" onmouseover="showStar({{idea.id}})" onmouseout="hideStar({{idea.id}})" onclick="toggleFavorite({{idea.id}})">
            {% if idea.image.url != null and idea.image.url != '' %}
              <img src="{{idea.image.url}}">
            {% else %}
              <img src="{% static "ideas/image/no_img.png" %}" alt="대체 텍스트">
            {% endif %}

            {% if idea.ideastar.star == True %}
              <div class="star" id="star-{{idea.id}}" style="display:block;">&#9734;</div>
            {% else %}
              <div class="star" id="star-{{idea.id}}" style="display:none;">&#9734;</div>
            {% endif %}
          </div>
          <div class="info">
            <a href="{% url 'ideas:detail' idea.pk %}" class="title">
              {{idea.title}}
            </a>
            <p class="region"> 예상 개발 툴 : {{idea.devtool.name}}</p>
            {% csrf_token %}
            <div id="inter"> 
              <a onclick="fetchpage({{idea.id}}, 1)">+</a>
              <span id="interest-lev-{{idea.id}}">{{idea.interest}}</span>
              <a onclick="fetchpage({{idea.id}}, -1)">-</a>
            </div>
          </div>
        </div>
      {% endfor %}

    </div>
    <div class="pagination">
      <span class="step-links">
          {% if ideas.has_previous %}
              <a href="?page=1&sort={{ order_by_field }}">&laquo; first</a>
              <a href="?page={{ ideas.previous_page_number }}&sort={{ order_by_field }}">previous</a>
          {% endif %}
  
          <span class="current">
              Page {{ ideas.number }} of {{ ideas.paginator.num_pages }}.
          </span>
  
          {% if ideas.has_next %}
              <a href="?page={{ ideas.next_page_number }}&sort={{ order_by_field }}">next</a>
              <a href="?page={{ ideas.paginator.num_pages }}&sort={{ order_by_field }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
  </div>
  <script>
    function fetchpage(id, num){
      console.log(typeof(num));
      i="interest-lev-"+id;
      console.log(i);
      const inter=document.getElementById(i);
      if(num==1){
        inter.innerHTML = parseInt(inter.innerHTML) + 1;
      }
      else{
        inter.innerHTML = parseInt(inter.innerHTML) - 1;
      }
      console.log(inter)
      $.ajax({
        url: '/change_interest/', // URL 인코딩
        data: jQuery.param({ field1: id, field2 : num}) ,
        method: 'POST',
        dataType: 'json',
        headers: {
            'X-CSRFToken': csrftoken
        },
        success: function (data) {
          console.log("success");
        },
        error: function (error) {
            console.log('Error:', error);
        }
      });
    }
  </script>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_update.html
{% extends 'base.html' %}
{%block head%}
  <title>idea_create</title>
{% endblock %}

{%block content%}
  <div class="content-wrapper-2">
    <div class="wrapper-header">
      <h2>Idea Register</h2>
      <p>아이디어 세부내용 수정 페이지입니다. 수정사항이 있다면 수정하세요!</p>
    </div>
    <form
      action="{% url 'ideas:update' pk %}"
      method="post"
      enctype="multipart/form-data"
    >
      {%csrf_token%} {{form.as_p}}
      <button class="btn btn-success">수정하기</button>
    </nctype=>
  </div>
{%endblock%}